"""Add link column to Notification model

Revision ID: 59455d88b633
Revises: 9611dbe973b0
Create Date: 2025-10-23 09:52:30.744373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59455d88b633'
down_revision = '9611dbe973b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###
