"""Cascade delete attendance logs on student delete

Revision ID: 67270cff6738
Revises: 59455d88b633
Create Date: 2025-10-23 10:18:03.959781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67270cff6738'
down_revision = '59455d88b633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('attendance_log_ibfk_4'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attendance_log_ibfk_4'), 'student', ['student_id'], ['id'])

    # ### end Alembic commands ###
