"""Cascade delete attendance logs on student delete

Revision ID: 89ca82efae25
Revises: 67270cff6738
Create Date: 2025-10-23 10:20:09.552755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89ca82efae25'
down_revision = '67270cff6738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_log', schema=None) as batch_op:
        batch_op.alter_column('card_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('attendance_log_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'card', ['card_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attendance_log_ibfk_1'), 'card', ['card_id'], ['id'])
        batch_op.alter_column('card_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
