"""Add NotificationType enum and type column to Notification model

Revision ID: 9611dbe973b0
Revises: 61c1150f3900
Create Date: 2025-10-23 09:21:39.284989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9611dbe973b0'
down_revision = '61c1150f3900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_log', schema=None) as batch_op:
        batch_op.alter_column('final_status',
               existing_type=mysql.ENUM('PRESENT', 'LATE', 'ABSENT', 'EXCUSED_ABSENCE', 'UNKNOWN'),
               type_=sa.Enum('PRESENT', 'LATE', 'ABSENT', 'EXCUSED', 'UNKNOWN', name='finalattendancestatus'),
               existing_nullable=True)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('GENERAL', 'ATTENDANCE_UPDATE', 'EXCUSE_STATUS', name='notificationtype'), nullable=False))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('attendance_log', schema=None) as batch_op:
        batch_op.alter_column('final_status',
               existing_type=sa.Enum('PRESENT', 'LATE', 'ABSENT', 'EXCUSED', 'UNKNOWN', name='finalattendancestatus'),
               type_=mysql.ENUM('PRESENT', 'LATE', 'ABSENT', 'EXCUSED_ABSENCE', 'UNKNOWN'),
               existing_nullable=True)

    # ### end Alembic commands ###
